.PHONY: fmt validate test readme docs ci tofu-fmt tofu-validate terragrunt-validate security tflint

MODULES := $(shell find modules -maxdepth 1 -mindepth 1 -type d 2>/dev/null)
EXAMPLES := $(shell find examples -maxdepth 1 -mindepth 1 -type d 2>/dev/null)

fmt:
	terraform fmt -recursive

validate:
	terraform init -backend=false
	terraform validate
	@for m in $(MODULES); do \
		echo "==> validating $$m"; \
		terraform -chdir=$$m init -backend=false >/dev/null && \
		terraform -chdir=$$m validate || exit 1; \
	done

test:
	terraform test
	@for m in $(MODULES); do \
		if [ -d "$$m/tests" ]; then \
			echo "==> testing $$m"; \
			terraform -chdir=$$m init -backend=false >/dev/null && \
			terraform -chdir=$$m test || exit 1; \
		fi; \
	done

tofu-fmt:
	tofu fmt -recursive

tofu-validate:
	tofu init -backend=false
	tofu validate

terragrunt-validate:
	cd examples/terragrunt && terragrunt validate

# --recursive resolves .tflint.hcl relative to each target directory, so the
# root config must be passed explicitly with an absolute path.
tflint:
	@command -v tflint >/dev/null 2>&1 || (echo "tflint is required"; exit 1)
	tflint --init
	tflint --recursive -f compact --config "$(CURDIR)/.tflint.hcl"

security:
	@command -v gitleaks >/dev/null 2>&1 || (echo "gitleaks is required"; exit 1)
	@command -v checkov >/dev/null 2>&1 || (echo "checkov is required"; exit 1)
	gitleaks detect --source . --verbose
	checkov -d . --compact

# README.md is generated by geine from README.yaml. Never hand-edit README.md.
#
# The CloudDrove readme workflow clones geine into ./genie and runs `make readme`
# on a runner that has no gomplate, so this target locates the template in either
# place and fetches gomplate when it is missing rather than failing.
GOMPLATE_VERSION ?= v5.2.0
GENIE_PATH ?= $(firstword $(wildcard ./genie $(HOME)/workspace/clouddrove/bob/genie))
README_TEMPLATE := $(firstword $(wildcard $(GENIE_PATH)/views/README.md ./genie/views/README.md))
export README_YAML ?= README.yaml
export README_INCLUDES ?= file://$(CURDIR)/?type=application/array+yaml

readme:
	@test -n "$(README_TEMPLATE)" || { \
		echo "geine template not found. Clone https://github.com/clouddrove/geine and set GENIE_PATH."; \
		exit 1; \
	}
	@if command -v gomplate >/dev/null 2>&1; then \
		GOMPLATE=gomplate; \
	else \
		echo "gomplate not found, fetching $(GOMPLATE_VERSION)"; \
		mkdir -p .bin; \
		os=$$(uname -s | tr '[:upper:]' '[:lower:]'); \
		arch=$$(uname -m | sed 's/x86_64/amd64/; s/aarch64/arm64/'); \
		curl -sSLo .bin/gomplate "https://github.com/hairyhenderson/gomplate/releases/download/$(GOMPLATE_VERSION)/gomplate_$${os}-$${arch}"; \
		chmod +x .bin/gomplate; \
		GOMPLATE=$(CURDIR)/.bin/gomplate; \
	fi; \
	$$GOMPLATE --file $(README_TEMPLATE) --out README.md
	@echo "Generated README.md from $(README_TEMPLATE) using $(README_YAML)"

docs:
	@command -v terraform-docs >/dev/null 2>&1 || (echo "terraform-docs is required"; exit 1)
	@for m in $(MODULES); do \
		terraform-docs markdown table --output-file README.md --output-mode inject $$m; \
	done
	@for e in $(EXAMPLES); do \
		terraform-docs markdown table --output-file README.md --output-mode inject $$e; \
	done

ci: fmt validate test
