.PHONY: fmt validate test readme docs ci tofu-fmt tofu-validate terragrunt-validate security tflint

MODULES := $(shell find modules -maxdepth 1 -mindepth 1 -type d 2>/dev/null)
EXAMPLES := $(shell find examples -maxdepth 1 -mindepth 1 -type d 2>/dev/null)

fmt:
	terraform fmt -recursive

validate:
	terraform init -backend=false
	terraform validate
	@for m in $(MODULES); do \
		echo "==> validating $$m"; \
		terraform -chdir=$$m init -backend=false >/dev/null && \
		terraform -chdir=$$m validate || exit 1; \
	done

test:
	terraform test
	@for m in $(MODULES); do \
		if [ -d "$$m/tests" ]; then \
			echo "==> testing $$m"; \
			terraform -chdir=$$m init -backend=false >/dev/null && \
			terraform -chdir=$$m test || exit 1; \
		fi; \
	done

tofu-fmt:
	tofu fmt -recursive

tofu-validate:
	tofu init -backend=false
	tofu validate

terragrunt-validate:
	cd examples/terragrunt && terragrunt validate

# --recursive resolves .tflint.hcl relative to each target directory, so the
# root config must be passed explicitly with an absolute path.
tflint:
	@command -v tflint >/dev/null 2>&1 || (echo "tflint is required"; exit 1)
	tflint --init
	tflint --recursive -f compact --config "$(CURDIR)/.tflint.hcl"

security:
	@command -v gitleaks >/dev/null 2>&1 || (echo "gitleaks is required"; exit 1)
	@command -v checkov >/dev/null 2>&1 || (echo "checkov is required"; exit 1)
	gitleaks detect --source . --verbose
	checkov -d . --compact

# README.md is generated by geine from README.yaml. Never hand-edit README.md.
# GENIE_PATH defaults to the usual sibling checkout; override it if yours differs.
export GENIE_PATH ?= $(HOME)/workspace/clouddrove/bob/genie
export README_YAML ?= README.yaml
export README_INCLUDES ?= file://$(CURDIR)/?type=application/array+yaml

readme:
	@command -v gomplate >/dev/null 2>&1 || (echo "gomplate is required: brew install gomplate"; exit 1)
	@test -f "$(GENIE_PATH)/views/README.md" || (echo "geine template not found at $(GENIE_PATH); set GENIE_PATH"; exit 1)
	gomplate --file $(GENIE_PATH)/views/README.md --out README.md

docs:
	@command -v terraform-docs >/dev/null 2>&1 || (echo "terraform-docs is required"; exit 1)
	@for m in $(MODULES); do \
		terraform-docs markdown table --output-file README.md --output-mode inject $$m; \
	done
	@for e in $(EXAMPLES); do \
		terraform-docs markdown table --output-file README.md --output-mode inject $$e; \
	done

ci: fmt validate test
