name: tf-checks

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '*.tf'
jobs:
  basic:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/basic/'
      provider: none
  complete:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/complete/'
      provider: none
  secrets-sync:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/secrets-sync/'
      provider: none
